/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * Package: @inneranimalmedia/ecommerce-cms-agentsam
 * Feature: Autonomous CampaignBuilder & Growth View
 */

import React, { useState } from 'react';
import { Card } from '../../design-system/Card';
import { Badge } from '../../design-system/Badge';
import { Button } from '../../design-system/Button';
import { Input } from '../../design-system/Input';
import { Select } from '../../design-system/Select';
import {
  Rocket,
  Sparkles,
  Send,
  Mail,
  Instagram,
  CheckCircle2,
  Copy,
  Layers,
  ArrowRight,
  RefreshCw,
  Clock
} from 'lucide-react';
import { useToast } from '../../design-system/Toast';

interface GeneratedCampaignPackage {
  title: string;
  goal: string;
  emailSubject: string;
  emailPreview: string;
  emailBody: string;
  bannerHeadline: string;
  bannerSub: string;
  socialCaption: string;
  hashtags: string[];
  utmUrl: string;
}

export const GrowthView: React.FC = () => {
  const { addToast } = useToast();
  const [goal, setGoal] = useState('Fall DTG Vintage Drop Launch');
  const [audience, setAudience] = useState('Vintage Motocross & Trackside Enthusiasts');
  const [discountCode, setDiscountCode] = useState('TRACKSIDE15');
  const [isGenerating, setIsGenerating] = useState(false);
  const [campaignPackage, setCampaignPackage] = useState<GeneratedCampaignPackage | null>({
    title: 'Fall 2026 Vintage Trackside Drop',
    goal: 'Promote newly mapped Completeful DTG washed hoodies and tees with a 15% limited code.',
    emailSubject: '🏁 New Drop Alert: Trackside Heavyweight Hoodies Are Here',
    emailPreview: 'Pre-shrunk cotton fleece, vintage graphics, and track-ready durability.',
    emailBody: `Hey Rider,\n\nWe just unloaded our latest garage drop. Crafted for cold track mornings and late-night wrenching sessions, our new Heavyweight DTG Hoodies feature authentic Fuel & Free Time artwork backed by durable double-needle seams.\n\nUse code TRACKSIDE15 at checkout for 15% off during launch week.`,
    bannerHeadline: 'AUTHENTIC MOTORSPORT HERITAGE // FALL DROP LIVE',
    bannerSub: 'Heavyweight DTG hoodies and vintage tees engineered for trackside wear.',
    socialCaption: 'Built for the track. Worn in the garage. 🏁 Our Fall apparel collection is officially live. Drop a comment with your favorite piece below.',
    hashtags: ['#FuelNFreeTime', '#TracksideCulture', '#VintageMoto', '#GarageBuilt'],
    utmUrl: 'https://fuelnfreetime.com/drops/fall-2026?utm_source=email&utm_medium=broadcast&utm_campaign=fall_drop_2026'
  });

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setCampaignPackage({
        title: `${goal} Campaign Package`,
        goal: `Engineered campaign for target audience: ${audience}`,
        emailSubject: `🔥 Special Release: ${goal} is Live Now`,
        emailPreview: `Exclusive apparel drop with limited promo code ${discountCode}.`,
        emailBody: `Hey Free Timers,\n\nOur latest collection is officially unlocked. Explore the newest Completeful print-on-demand drop before inventory blanks sell out.\n\nClaim ${discountCode} at checkout today.`,
        bannerHeadline: `${goal.toUpperCase()} // NOW LIVE`,
        bannerSub: `Curated apparel and trackside merchandise. Available for a limited run.`,
        socialCaption: `The countdown is over. The new drop is live now on the storefront! Head to the link in bio to grab yours with code ${discountCode}. 🚀`,
        hashtags: ['#FuelNFreeTime', '#MotorsportGear', '#NewDrop', '#LimitedRun'],
        utmUrl: `https://fuelnfreetime.com/store?utm_source=resend&utm_campaign=${encodeURIComponent(
          goal.toLowerCase().replace(/\s+/g, '_')
        )}&utm_coupon=${discountCode}`
      });
      addToast({
        type: 'success',
        title: 'Campaign Package Generated',
        description: 'Multi-channel assets generated by AgentSam host AI engine.'
      });
    }, 1200);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-zinc-100">
            Autonomous CampaignBuilder
          </h1>
          <p className="text-xs text-zinc-400 mt-0.5">
            Formulate multi-channel drop packages with coordinated email broadcasts, storefront banners, and social copy.
          </p>
        </div>

        <Badge variant="amber" size="md">
          AgentSam Growth Engine
        </Badge>
      </div>

      {/* Generator Configuration Card */}
      <Card padding="lg">
        <h3 className="text-sm font-semibold text-zinc-100 mb-4 flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-400" />
          <span>Configure Drop Brief & Parameters</span>
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Input
            label="Campaign Goal / Drop Theme"
            value={goal}
            onChange={(e) => setGoal(e.target.value)}
            placeholder="e.g. Vintage Hoodie Release"
          />
          <Input
            label="Target Audience"
            value={audience}
            onChange={(e) => setAudience(e.target.value)}
            placeholder="e.g. Trackside Motorcycle Riders"
          />
          <Input
            label="Promotional Discount Code"
            value={discountCode}
            onChange={(e) => setDiscountCode(e.target.value)}
            placeholder="e.g. TRACKSIDE15"
          />
        </div>

        <div className="mt-4 pt-4 border-t border-zinc-800 flex justify-end">
          <Button
            size="sm"
            variant="primary"
            isLoading={isGenerating}
            icon={<Sparkles className="w-3.5 h-3.5" />}
            onClick={handleGenerate}
          >
            Generate Multi-Channel Package
          </Button>
        </div>
      </Card>

      {/* Generated Assets Display */}
      {campaignPackage && (
        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-zinc-200">
            Generated Multi-Channel Package
          </h3>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Email Broadcast Package */}
            <Card padding="md" className="space-y-3">
              <div className="flex items-center justify-between border-b border-zinc-800 pb-2.5">
                <div className="flex items-center gap-2">
                  <Mail className="w-4 h-4 text-amber-400" />
                  <span className="font-semibold text-xs text-zinc-200">
                    Resend Email Broadcast
                  </span>
                </div>
                <Badge variant="emerald" size="sm">
                  Ready to Dispatch
                </Badge>
              </div>

              <div className="space-y-2 text-xs">
                <div>
                  <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-wider block">
                    Subject Line
                  </span>
                  <span className="font-semibold text-zinc-200 block">
                    {campaignPackage.emailSubject}
                  </span>
                </div>
                <div>
                  <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-wider block">
                    Preview Text
                  </span>
                  <span className="text-zinc-400 block">{campaignPackage.emailPreview}</span>
                </div>
                <div>
                  <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-wider block">
                    Body Copy
                  </span>
                  <p className="p-3 rounded-xl bg-zinc-900/60 border border-zinc-800 text-zinc-300 whitespace-pre-line text-xs font-sans">
                    {campaignPackage.emailBody}
                  </p>
                </div>
              </div>
            </Card>

            {/* Storefront Banner & Social Copy */}
            <div className="space-y-6">
              {/* Banner */}
              <Card padding="md" className="space-y-2">
                <div className="flex items-center gap-2 border-b border-zinc-800 pb-2">
                  <Layers className="w-4 h-4 text-sky-400" />
                  <span className="font-semibold text-xs text-zinc-200">
                    Storefront Hero Banner Copy
                  </span>
                </div>
                <div className="p-3.5 rounded-xl bg-gradient-to-r from-amber-500/10 via-zinc-900 to-zinc-900 border border-amber-500/20">
                  <h4 className="font-bold text-xs font-mono text-amber-300 uppercase tracking-wide">
                    {campaignPackage.bannerHeadline}
                  </h4>
                  <p className="text-xs text-zinc-300 mt-1">{campaignPackage.bannerSub}</p>
                </div>
              </Card>

              {/* Social Media */}
              <Card padding="md" className="space-y-2">
                <div className="flex items-center gap-2 border-b border-zinc-800 pb-2">
                  <Instagram className="w-4 h-4 text-pink-400" />
                  <span className="font-semibold text-xs text-zinc-200">
                    Social Media Caption & Tags
                  </span>
                </div>
                <div className="p-3 rounded-xl bg-zinc-900/60 border border-zinc-800 text-xs text-zinc-300 space-y-2">
                  <p>{campaignPackage.socialCaption}</p>
                  <div className="flex flex-wrap gap-1 pt-1 font-mono text-[11px] text-amber-400">
                    {campaignPackage.hashtags.join(' ')}
                  </div>
                </div>
              </Card>

              {/* UTM URL */}
              <Card padding="sm" className="flex items-center justify-between gap-2">
                <div className="min-w-0">
                  <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-wider block">
                    Campaign Tracking URL
                  </span>
                  <span className="text-[11px] font-mono text-zinc-300 truncate block">
                    {campaignPackage.utmUrl}
                  </span>
                </div>
                <Button
                  size="xs"
                  variant="outline"
                  icon={<Copy className="w-3 h-3" />}
                  onClick={() => {
                    navigator.clipboard.writeText(campaignPackage.utmUrl);
                    addToast({
                      type: 'success',
                      title: 'Copied to Clipboard',
                      description: 'UTM campaign link copied.'
                    });
                  }}
                >
                  Copy
                </Button>
              </Card>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
